#!/usr/bin/env bash
# Build + screenshot each app page from the Connect IQ simulator, headlessly.
#
# The simulator has no scriptable input (osascript needs assistive access), so
# paging is done by temporarily rewriting getInitialView() to open the page we
# want, then capturing the simulator window by its CoreGraphics window id.
#
# Requires a python with pyobjc-framework-Quartz on PYTHON (see scripts/sim-window-id.py).
#
# Usage: scripts/shoot-pages.sh [outdir]
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$REPO/.screenshots}"
DEVICE="fr57047mm"
APP="$REPO/watch/source/ClaudePulseApp.mc"
SDK="$(ls -d "$HOME/Library/Application Support/Garmin/ConnectIQ/Sdks"/*/bin | tail -1)"
PYTHON="${PYTHON:-python3}"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk}"

mkdir -p "$OUT"
SEED="$REPO/watch/source/_ScreenshotSeed.mc"
cp "$APP" "$APP.bak"
trap 'mv -f "$APP.bak" "$APP"; rm -f "$SEED"' EXIT

# The simulator has no relay, so the pages would render "--" everywhere. Seed a
# snapshot matching the mockup's numbers.
#
# This is generated here, and deleted by the trap above, rather than living in
# watch/source: a seeder committed to the tree is one someone eventually ships
# to the store with fake data baked in.
# Reset times are absolute in the snapshot, so they are computed here relative
# to now — the views turn them back into "resets in 2h 15m" / "3d 7h".
FIVE_RESET="$(date -u -v+2H -v+15M +%Y-%m-%dT%H:%M:%SZ)"
SEVEN_RESET="$(date -u -v+3d -v+7H +%Y-%m-%dT%H:%M:%SZ)"

cat > "$SEED" <<SEEDEOF
// GENERATED by scripts/shoot-pages.sh — deleted when it exits. Do not commit.
import Toybox.Lang;
import Toybox.Time;

module ScreenshotSeed {
    function apply() as Void {
        var now = Time.now().value();
        var daily = [
            {"day" => "2026-07-28", "cost_usd" => 6.40, "tokens" => 910000},
            {"day" => "2026-07-29", "cost_usd" => 11.20, "tokens" => 1600000},
            {"day" => "2026-07-30", "cost_usd" => 4.10, "tokens" => 580000},
            {"day" => "2026-07-31", "cost_usd" => 15.90, "tokens" => 2250000},
            {"day" => "2026-08-01", "cost_usd" => 9.70, "tokens" => 1380000},
            {"day" => "2026-08-02", "cost_usd" => 12.30, "tokens" => 1740000},
            {"day" => "2026-08-03", "cost_usd" => 14.82, "tokens" => 2100000}
        ];
        Snap.save({
            "five_hour_pct" => 68,
            "seven_day_pct" => 42,
            "is_active" => true,
            "active_count" => 2,
            "five_hour_resets_at" => "$FIVE_RESET",
            "seven_day_resets_at" => "$SEVEN_RESET",
            "today_cost_usd" => 14.82,
            "today_tokens" => 2100000,
            "daily" => daily
        }, now);
    }
}
SEEDEOF

shoot() { # shoot <view-class> <page-name>
  perl -0pi -e "s/return \[new \w+View\(\), new PageDelegate\(\d\)\]/return [new $1(), new PageDelegate(0)]/" "$APP"
  # Without a glance entry point the simulator has to open the app view.
  perl -0pi -e "s/function getGlanceView\(/function getGlanceViewDisabled(/" "$APP"
  # Seed the fake snapshot before the first view is built.
  perl -0pi -e "s/(function onStart\(state as Dictionary\?\) as Void \{)/\$1\n        ScreenshotSeed.apply();/" "$APP"
  "$SDK/monkeyc" -f "$REPO/watch/monkey.jungle" -d "$DEVICE" \
    -o /tmp/ClaudePulse-shot.prg -y "$REPO/developer_key.der" >/dev/null
  pkill -f monkeydo 2>/dev/null || true
  sleep 3
  # A simulator left in glance-preview mode keeps showing the glance strip for
  # every later launch, so start from a fresh simulator process each time.
  pkill -f 'ConnectIQ.app/Contents/MacOS' 2>/dev/null || true
  sleep 2
  ("$SDK/connectiq" >/tmp/connectiq-shot.log 2>&1 &)
  sleep 25
  ("$SDK/monkeydo" /tmp/ClaudePulse-shot.prg "$DEVICE" >/tmp/monkeydo-shot.log 2>&1 &)
  sleep 15
  screencapture -o -x -l "$("$PYTHON" "$REPO/scripts/sim-window-id.py")" "$OUT/$2.png"
  echo "wrote $OUT/$2.png"
}

shoot RingsView  page-1-rings
shoot DetailView page-2-detail
shoot CostView   page-3-cost
rm -f "$OUT/_full.png"
